import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";

export function CameraPage() {
  const video = useRef(null); const stream = useRef(null); const [active, setActive] = useState(false); const [status, setStatus] = useState("Inactive"); const [resolution, setResolution] = useState("—"); const [error, setError] = useState(null);
  const stop = () => { stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; if (video.current) video.current.srcObject = null; setActive(false); setStatus("Inactive"); setResolution("—"); };
  useEffect(() => stop, []);
  const start = async () => { setError(null); setStatus("Requesting camera access…"); try { const media = await navigator.mediaDevices.getUserMedia({ video: { width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); stream.current = media; video.current.srcObject = media; video.current.onloadedmetadata = () => { setResolution(`${video.current.videoWidth} × ${video.current.videoHeight}`); setActive(true); setStatus("Live"); }; } catch (reason) { setStatus("Camera access failed"); setError(reason.name === "NotAllowedError" ? "Camera access was denied by the browser." : reason.name === "NotFoundError" ? "No webcam was found." : `Could not start camera preview: ${reason.message}`); } };
  return <section className="camera-page"><header className="camera-heading"><div><h2>Camera preview</h2><p>Inspect framing and alignment before configuring an experiment.</p></div></header>{error && <section className="alert error">{error}</section>}<div className="camera-layout"><section className="camera-preview-card card"><div className="camera-stage"><video ref={video} autoPlay muted playsInline hidden={!active} />{!active && <div className="camera-placeholder"><span className="camera-placeholder-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M8.5 6 10 4h4l1.5 2H19a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h3.5Z"/><circle cx="12" cy="12.5" r="3.5"/></svg></span><h3>Camera inactive</h3><p>Start the preview to inspect alignment.</p></div>}</div><div className="camera-controls"><button type="button" onClick={start} disabled={active}>Start camera</button><button type="button" className="secondary" onClick={stop} disabled={!active}>Stop camera</button></div></section><aside className="camera-info-card card"><h3>Preview status</h3><dl className="camera-status-list"><div><dt>Status</dt><dd>{status}</dd></div><div><dt>Resolution</dt><dd>{resolution}</dd></div></dl></aside></div><footer className="camera-workflow-footer"><div><strong>Camera preview is optional during development</strong><p>This browser preview does not verify the Raspberry Pi capture camera while <code>capture_once.py</code> remains a stub.</p></div><Link className="camera-continue-link" to="/schedule">Continue to schedule setup <span aria-hidden="true">→</span></Link></footer></section>;
}
