import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../api";
import { ErrorNotice, Loading, SchedulePreview, WorkflowSteps } from "../components";

export function ScheduleReviewPage() {
  const navigate = useNavigate(); const [review, setReview] = useState(null); const [error, setError] = useState(null); const [confirm, setConfirm] = useState(false); const [replacementAccepted, setReplacementAccepted] = useState(false); const [working, setWorking] = useState(false);
  useEffect(() => { api("/api/schedule/draft").then(setReview).catch(reason => { if (reason.message.includes("No schedule draft")) navigate("/schedule", { replace: true }); else setError(reason); }); }, [navigate]);
  if (!review && !error) return <Loading label="Loading schedule review" />;
  if (!review) return <ErrorNotice error={error} />;
  const activate = async confirmed => { setWorking(true); setError(null); try { const result = await api("/api/schedule/activate", { method: "POST", body: JSON.stringify({ draft_hash: review.draft.schedule_hash, confirm_active_replacement: confirmed }) }); if (result.confirmation_required) { setConfirm(true); setReview(result.review); } else navigate(`/schedule/activation?schedule_hash=${result.schedule_hash}${review.analysis_requested ? "&analysis=1" : ""}`); } catch (reason) { setError(reason); } finally { setWorking(false); } };
  const discard = async () => { await api("/api/schedule/draft", { method: "DELETE" }); navigate("/schedule"); };
  const storage = review.storage_assessment;
  const replacingActive = review.scheduler_status?.schedule?.lifecycle === "active";
  return <><WorkflowSteps current={review.analysis_requested ? (confirm ? 5 : 4) : (confirm ? 4 : 3)} analysisEnabled={review.analysis_requested} /><section className="workflow-heading"><span className="eyebrow">Draft schedule</span><h2>Review before activation</h2><p><strong>{review.draft.form.experiment_name}</strong> · Verify the complete schedule before activation.</p></section><ErrorNotice error={error} />
    {review.already_active && <section className="schedule-match-notice" role="status"><strong>This schedule is already active</strong><p>No activation is needed.</p></section>}
    {confirm && <section className="activation-confirmation" role="alert"><h3>{replacingActive ? "Replace the schedule during an active experiment?" : "Replace the upcoming experiment schedule?"}</h3><p>{replacingActive ? "This changes the remaining planned captures." : "The currently scheduled experiment will not run."}</p><label className="confirmation-check"><input type="checkbox" checked={replacementAccepted} onChange={event => setReplacementAccepted(event.target.checked)} /> {replacingActive ? "I understand that this changes the active experiment." : "I understand that this replaces the upcoming experiment."}</label><div className="actions"><button className="secondary" onClick={() => { setConfirm(false); setReplacementAccepted(false); }}>Cancel</button><button className="danger-button" disabled={!replacementAccepted || working} onClick={() => activate(true)}>{replacingActive ? "Replace active schedule" : "Replace upcoming schedule"}</button></div></section>}
    {review.comparison.has_active_schedule && <section className="comparison-card card"><div className="card-header"><div><h3>Changes from active schedule</h3><p>Changed values are highlighted.</p></div></div><div className="comparison-table" role="table"><div className="comparison-row comparison-row--header" role="row"><strong>Setting</strong><strong>Active</strong><strong>Draft</strong></div>{review.comparison.rows.map(row => <div className={`comparison-row${row.changed ? " comparison-row--changed" : ""}`} role="row" key={row.label}><span>{row.label}</span><span>{row.active ?? "—"}</span><span className="comparison-draft">{row.draft}</span></div>)}</div></section>}
    <section className={`storage-preflight storage-preflight--${storage.status}`} role={storage.status === "insufficient" ? "alert" : "status"}><h3>{storage.status === "insufficient" ? "Not enough storage for this experiment" : storage.status === "unverified" ? "Storage could not be verified" : "Storage available"}</h3><p>{storage.status === "insufficient" ? <>The protected estimate is <strong>{storage.required_label}</strong>, but only <strong>{storage.free_label}</strong> is free.</> : storage.status === "unverified" ? <>This experiment is estimated to need <strong>{storage.required_label}</strong>.</> : <>Estimated requirement: <strong>{storage.required_label}</strong>; currently free: <strong>{storage.free_label}</strong>.</>}</p><small>Includes 7.6 MB captures and an equal reserve for measurements and secondary data.</small></section>
    <SchedulePreview preview={review.preview} />
    {review.analysis_requested && <section className={`card review-analysis-status${review.analysis_ready ? " review-analysis-status--ready" : " review-analysis-status--required"}`} role={review.analysis_ready ? "status" : "alert"}><div><span aria-hidden="true">{review.analysis_ready ? "✓" : "!"}</span><div><h3>{review.analysis_ready ? "Canopy analysis calibrated" : "Canopy calibration required"}</h3><p>{review.analysis_ready ? "This experiment includes the saved segmentation and ROI calibration." : "Complete the analysis setup before this experiment can be activated."}</p></div></div><Link className={review.analysis_ready ? "button-link secondary" : "primary-link"} to="/analysis?workflow=schedule">{review.analysis_ready ? "Review calibration" : "Calibrate analysis"}</Link></section>}
    <section className="review-actions card"><div><h3>Activate schedule</h3>{review.already_active ? <p>This schedule is already active.</p> : !review.camera_aligned ? <p className="blocked-copy">Camera alignment is required.</p> : !review.analysis_ready && review.analysis_requested ? <p className="blocked-copy">Canopy calibration is required.</p> : !review.scheduler_responding ? <p className="blocked-copy">Scheduler unavailable. Activation is paused.</p> : !review.can_activate ? <p className="blocked-copy">Free storage before activating.</p> : null}</div><div className="review-action-buttons"><button className="text-button" onClick={discard}>Discard draft</button><Link className="button-link secondary" to="/schedule/edit">Edit draft</Link><Link className="button-link secondary" to="/camera?workflow=schedule">Review alignment</Link><button disabled={!review.can_activate || review.already_active || confirm || working} onClick={() => activate(false)}>{review.already_active ? "Already active" : working ? "Activating…" : "Activate schedule"}</button></div></section>
  </>;
}
