from __future__ import annotations

from datetime import date, datetime, timedelta
import json
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from .time_utils import parse_hhmm


def load_config(config_path: Path) -> dict[str, Any]:
    """
    Load a scheduler configuration from a JSON file.

    The configuration defines the start date, number of days, and capture
    times used to construct the schedule.

    Parameters
    ----------
    config_path : Path
        Path to the JSON configuration file.

    Returns
    -------
    dict[str, Any]
        Parsed configuration dictionary.

    Raises
    ------
    RuntimeError
        If the file does not exist or cannot be parsed as valid JSON.
    """
    try:
        return json.loads(config_path.read_text())
    except FileNotFoundError as exc:
        raise RuntimeError(
            f"Schedule config not found: {config_path}"
        ) from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Invalid JSON in config file: {config_path}"
        ) from exc


def load_completed_jobs(state_path: Path) -> set[str]:
    """
    Load previously completed job timestamps from a JSON file.

    The file is expected to contain a list of ISO-formatted datetime strings.
    If the file is missing or malformed, an empty set is returned.

    Parameters
    ----------
    state_path : Path
        Path to the JSON file storing completed job timestamps.

    Returns
    -------
    set[str]
        Set of ISO-formatted datetime strings representing completed jobs.
    """
    if not state_path.exists():
        return set()

    try:
        data = json.loads(state_path.read_text())
        if not isinstance(data, list):
            return set()
        return {str(item) for item in data}
    except Exception:
        return set()


def save_completed_jobs(state_path: Path, completed: set[str]) -> None:
    """
    Save completed job timestamps to a JSON file.

    The timestamps are written as a sorted list of ISO-formatted strings.
    The write is performed atomically via a temporary file to avoid corruption.

    Parameters
    ----------
    state_path : Path
        Path to the JSON file where completed jobs are stored.
    completed : set[str]
        Set of ISO-formatted datetime strings representing completed jobs.
    """
    tmp_path = state_path.with_suffix(".tmp")
    tmp_path.write_text(json.dumps(sorted(completed), indent=2))
    tmp_path.replace(state_path)


def build_schedule(cfg: dict[str, Any], tz: ZoneInfo) -> list[datetime]:
    """
    Construct a list of scheduled datetimes from a configuration.

    The schedule is generated by combining a start date, a number of days,
    and a list of daily times. Each resulting datetime is timezone-aware.

    Parameters
    ----------
    cfg : dict[str, Any]
        Configuration dictionary containing:
        - "start_date": ISO-formatted date string (YYYY-MM-DD)
        - "num_days": number of days to generate
        - "times": list of "HH:MM" time strings
    tz : ZoneInfo
        Timezone to assign to all generated datetimes.

    Returns
    -------
    list[datetime]
        Sorted list of timezone-aware datetimes representing scheduled jobs.

    Raises
    ------
    ValueError
        If required keys are missing, if values are invalid, or if time strings
        cannot be parsed.
    """
    try:
        start_date = date.fromisoformat(cfg["start_date"])
        num_days = int(cfg["num_days"])
        raw_times = cfg["times"]
    except KeyError as exc:
        raise ValueError(f"Missing required config key: {exc}") from exc

    if num_days <= 0:
        raise ValueError("num_days must be > 0")
    if not isinstance(raw_times, list) or not raw_times:
        raise ValueError("times must be a non-empty list of HH:MM strings")

    parsed_times = sorted({parse_hhmm(t) for t in raw_times})

    schedule: list[datetime] = []
    for day_offset in range(num_days):
        current_day = start_date + timedelta(days=day_offset)
        for parsed_time in parsed_times:
            schedule.append(
                datetime.combine(current_day, parsed_time, tzinfo=tz)
            )

    return schedule
